DROP TABLE IF EXISTS PRODUCT_CATEGORIES
GO

CREATE TABLE PRODUCT_CATEGORIES
(
	ID INT NOT NULL,
	NAME NVARCHAR(128)
	CONSTRAINT PK_PRODUCT_CATEGORIES_ID PRIMARY KEY (ID)
)
GO

CREATE UNIQUE INDEX UX_PRODUCT_CATEGORIES_NAME
	ON PRODUCT_CATEGORIES
(
	NAME
)
GO
