DROP TABLE IF EXISTS USERS
GO

CREATE TABLE USERS
(
	ID INT NOT NULL,
	UPDATE_COUNTER INT DEFAULT 0 NOT NULL,
	[ROLE] INT NOT NULL,
	FIRST_NAME NVARCHAR(128) NOT NULL,
	MIDDLE_NAME NVARCHAR(128) NOT NULL,
	LAST_NAME NVARCHAR(128) NOT NULL,
	EMAIL NVARCHAR(128) NOT NULL,
	PHONE NVARCHAR(32) NOT NULL,
	REGISTER_DATE DATETIME NOT NULL,
	DATE_OF_BIRTH DATETIME NOT NULL,
	PASSWORD NVARCHAR(512) NOT NULL,
	CONSTRAINT PK_USERS_ID PRIMARY KEY(ID)
)
GO

CREATE UNIQUE INDEX UX_USERS_PHONE
	ON USERS
(
	PHONE
)
GO

CREATE UNIQUE INDEX UX_USERS_EMAIL
	ON USERS
(
	EMAIL
)
GO

EXEC SP_ADD_NEW_COUNTER 'USERS', 'ID'
GO