CREATE TABLE PRODUCTS
(
	ID INT NOT NULL,
	NAME NVARCHAR(128) NOT NULL,
	PRODUCT_CATEGORY INT NOT NULL,
	IMAGE_URL VARCHAR(256) NOT NULL,
	DESCRIPTION NVARCHAR(512) NOT NULL,
	PRICE FLOAT NOT NULL,
	QUANTITY INT NOT NULL,
	CONSTRAINT PK_PRODUCTS_ID PRIMARY KEY(ID)
)
GO
CREATE UNIQUE INDEX UX_PRODUCTS_NAME
ON PRODUCTS
(
	NAME
)