CREATE TABLE PRODUCTS
(
	ID INT NOT NULL,
	UPDATE_COUNTER INT DEFAULT 0 NOT NULL,
	NAME NVARCHAR(128) NOT NULL,
	PRODUCT_CATEGORY INT NOT NULL,
	IMAGE_URL VARCHAR(256) NOT NULL,
	DESCRIPTION NVARCHAR(512) NOT NULL,
	PRICE FLOAT NOT NULL,
	QUANTITY INT NOT NULL,
	CONSTRAINT PK_PRODUCTS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_PRODUCTS_CATEGORIES_ID FOREIGN KEY(ID) 
	REFERENCES PRODUCT_CATEGORIES
)
GO
CREATE UNIQUE INDEX UX_PRODUCTS_NAME
ON PRODUCTS
(
	NAME
)