CREATE TABLE USER_SALTS
(
	ID INT NOT NULL,
	[USER_ID] INT NOT NULL,
	EMAIL VARCHAR(128) NOT NULL,
	SALT VARCHAR(128) NOT NULL,
	CONSTRAINT PK_USER_SALTS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_USER_SALTS_ID FOREIGN KEY([USER_ID]) 
	REFERENCES USERS(ID)
)